---
title: "NHD_R"
author: "Shayla Triantafillou"
date: "2025-02-18"
output: html_document
---

This code includes two parts: 1) Getting stream lines and 2) snapping user-input points to NHD streamlines (this is very useful to create input files for a batch StreamStats process)
Adapted from Ryan Peek: https://mapping-in-r-workshop.ryanpeek.org/03_vig_snapping_points_to_line.html

```{r}
#Install/load packages
source('setup.R')
```
# Part 1 - Get NHD streamlines

```{r}
#User input: coordinates at outlet of lowest downstream extent of study site. Input as (x, y), so (longitude, latitude)
river <- st_sfc(st_point(c(-114.07053834953288, 48.06269009013353)), crs = 4326)

#check class is "sfc" and "sfc_POINT"
class(river)

# Find the nearest stream segment ID to our point
river_comid <- discover_nhdplus_id(river)

# Make a list defining the sourcetype and ID
river_list <- list(featureSource = "comid", featureID = river_comid)

# get upstream flowlines
river_us_flowlines <- navigate_nldi(nldi_feature = river_list,
                                     mode = "UT", # "UT" for upstream with tributaries
                                     data_source = "",
                                     distance_km = 500) # Distance upstream from point it will stop navigating, a generous 500 for Swan

# Compile a list with all the comids we've identified:
all_comids_river <- c(river_us_flowlines[["UT_flowlines"]][["nhdplus_comid"]]) %>%
  as.numeric()

# Download all data and create a geopackage with the comid list
river_gpkg <- subset_nhdplus(comids=all_comids_river,
                              simplified = TRUE,
                              overwrite = TRUE,
                              output_file = paste0(here::here(), "/river_nhdplus.gpkg"),
                              nhdplus_data = "download",
                              return_data = FALSE)

# Check that there are correct layers in database:
st_layers(paste0(here::here(), "/river_nhdplus.gpkg"))

# Pull the flowlines back in to R as sf object
flowlines <- read_sf(paste0(here::here(), "/river_nhdplus.gpkg"), "NHDFlowline_Network")

# make a map

prettymapr::prettymap({
  rosm::osm.plot(project = FALSE, 
                 bbox = matrix(st_bbox(flowlines), byrow = FALSE, ncol = 2, 
                               dimnames = list(c("x", "y"), c("min", "max"))), 
                 type = "cartolight", quiet = TRUE, progress = "none")
  plot(flowlines$geom, col = "steelblue", lwd = (flowlines$streamorde / 4), add=TRUE)
  plot(river, add=TRUE, pch=21, bg="orange", cex=1.5)
  prettymapr::addnortharrow()
})

# Optional: Write as shapefile in folder connected to ArcPro. User updated file path

st_write(flowlines, "shapefiles/flowlines.shp", append=TRUE)
```


#Part 2 - snap user-input points to NHD flowlines

```{r}
## Get points from field data - example in "points" folder
reach_coordinates <- read_csv("points/points.csv") 


reach_coordinates <- reach_coordinates %>%
  drop_na(any_of(c("lat", "long")))

# Create spatial data set from csv
reach_sites <- st_as_sf(reach_coordinates, coords = c("long", "lat"), crs = 4326)

# Best to have everything in the same projection
if (st_crs(reach_sites) != st_crs(flowlines)) {
  reach_sites <- st_transform(reach_sites, st_crs(flowlines))
}
# Check that coordinate reference systems are the same
st_crs(reach_sites)==st_crs(flowlines)

# download all data and create a geopackage with the comid list
reach_geopckg <- subset_nhdplus(comids=river_comid,
                                   simplified = TRUE,
                                   overwrite = TRUE,
                                   output_file = paste0(here::here(), "/reach.gpkg"),
                                   nhdplus_data = "download",
                                   return_data = FALSE)


# Add these to our geopackage as well
st_write(reach_sites, "reach.gpkg", "reach_sites", append = TRUE)
st_write(flowlines, "reach.gpkg", "flowlines", append = TRUE)

#check layers
st_layers("reach.gpkg")


# write to geopackage: overwite the layer if it exists
st_write(reach_sites, dsn=paste0(here::here(),"/reach.gpkg"),
         layer="reach_sites", append = FALSE, delete_layer = TRUE)
st_layers(paste0(here::here(), "/reach.gpkg"))

# Map it - using ggplot here because I have been having issues loading other options like mapview, tmap, leaflet...the list of things not working goes on
ggplot() +
  geom_sf(data = river, color = "black", size = 1) +
  geom_sf(data = flowlines, aes(color = factor(streamorde)), size = 0.8) +
  # Plot reach sites as orange points
  geom_sf(data = reach_sites, color = "orange", size = 2) +
  scale_color_viridis_d(name = "Stream Order") +
  theme_minimal()

# # Alternate mapping strategy: use mapview package:
# m1 <- mapview(river, col.regions="black", cex=6, layer.name="river") + 
#   mapview(river_streams, zcol="streamorde", legend=TRUE, layer.name="Stream <br> Order") + 
#   mapview(reach_sites, col.regions="orange", layer.name="Reaches")
# 
# # add a measurement tool
# m1@map %>% leaflet::addMeasure(primaryLengthUnit = "kilometers") %>%
#   leaflet.extras::addFullscreenControl(position = "topleft")

# create function to snap points to the nearest line. This is a custom function from Tim Salabim on Stack Overflow
st_snap_points <- function(x, y, namevar, max_dist = 1000) {
  
  # this evaluates the length of the data
  if (inherits(x, "sf")) n = nrow(x)
  if (inherits(x, "sfc")) n = length(x)
  
  # this part: 
  # 1. loops through every piece of data (every point)
  # 2. snaps a point to the nearest line geometries
  # 3. calculates the distance from point to line geometries
  # 4. retains only the shortest distances and generates a point at that intersection
  out = do.call(c,
                lapply(seq(n), function(i) {
                  nrst = st_nearest_points(st_geometry(x)[i], y)
                  nrst_len = st_length(nrst)
                  nrst_mn = which.min(nrst_len)
                  if (as.vector(nrst_len[nrst_mn]) > max_dist) return(st_geometry(x)[i])
                  return(st_cast(nrst[nrst_mn], "POINT")[2])
                })
  )
  # this part converts the data to a dataframe and adds a named column of your choice
  out_xy <- st_coordinates(out) %>% as.data.frame()
  out_xy[[namevar]] <- x[[namevar]]  # Use direct column extraction
  out_xy <- st_as_sf(out_xy, coords=c("X","Y"), crs=st_crs(x), remove=FALSE)
  
  return(out_xy)
} 

#Prepare to use function
# check for duplicates and correct number of reaches
reach_sites %>% distinct(id) %>% nrow()

# use custom function to snap our reach boundaries to our flowline, using a buffer of 100 meters. We need to project our data here for this to work correctly.

# first project
reach_sites_proj <- st_transform(reach_sites, crs = 26910)
streams_proj <- st_transform(flowlines, crs=26910)

# Use the function! Snap points to the lines using a 500 meter buffer, select which ID column you want keep for rejoining
sites_snapped <- st_snap_points(reach_sites_proj, streams_proj, namevar = "id", max_dist = 600)

#Check the first few rows to see if it worked
head(sites_snapped) # Yay, it worked!

# Write the snapped points to output folder
st_write(sites_snapped, "points/output/sites_snapped.gpkg") # Write to a GeoPackage first
print(st_read("points/output/sites_snapped.gpkg")) # Check column names

st_write(sites_snapped, "points/output/sites_snapped.shp", append = TRUE)


# #Map it interactively with mapview to make sure that points snapped correctly
# mapview(sites_snapped, col.regions="cyan", layer.name="Snapped reach sites") +
#   mapview(streams_proj, color="steelblue", layer.name="Flowlines") +
#   mapview(reach_sites, col.regions="orange", layer.name="reach Sites")
```
# Part 3? - Split the line segments by points

```{r}

# create a 1 meter buffer around snapped point
sites_snapped_buff <- st_buffer(sites_snapped, 1)

# now use lwgeom::st_split to split stream segments by the snapped points 
# Note: if using NHD lines, this will not dissolve any segments, only split, to preserve the data (stream order, etc.) associated with each segment.

# Alternate: if you want stream segments to be 1:1 for each reach, use st_union() first:

# streams_proj_union <- st_union(streams_proj)

segments <- st_collection_extract(lwgeom::st_split(streams_proj, sites_snapped_buff), "LINESTRING") %>% 
  tibble::rownames_to_column(var = "rowid") %>% 
  mutate(rowid=as.integer(rowid))

st_write(segments, "segments.shp", append = TRUE)

```

```{r}

```

